import { RELATIVE_URLS } from "@/config/urls";

export const INTERNAL_LINKS = [
  // Product
  {
    href: RELATIVE_URLS.INDEX,
    eventType: "home",
    text: "Home",
    category: "product",
    showInHeader: true,
    showInMobile: true,
  },
  {
    href: RELATIVE_URLS.WHY_GITAUTO,
    eventType: "why_gitauto",
    text: "Why GitAuto",
    category: "product",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.WHAT_GITAUTO_DOES,
    eventType: "what_gitauto_does",
    text: "What GitAuto Does",
    category: "product",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.HOW_IT_WORKS,
    eventType: "how_it_works",
    text: "How It Works",
    category: "product",
    showInHeader: false,
    showInMobile: true,
  },
  {
    href: RELATIVE_URLS.USE_CASES,
    eventType: "use_cases",
    text: "Use Cases",
    category: "product",
    showInHeader: false,
    showInMobile: true,
  },
  {
    href: RELATIVE_URLS.HOW_TO_GET_STARTED,
    eventType: "how_to_get_started",
    text: "How to Get Started",
    category: "product",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.PRICING,
    eventType: "pricing",
    text: "Pricing",
    category: "product",
    showInHeader: true,
    showInMobile: true,
  },
  {
    href: RELATIVE_URLS.PRICING_DETAILS,
    eventType: "pricing_details",
    text: "Pricing Details",
    category: "product",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.ROI.CALCULATOR,
    eventType: "roi_calculator",
    text: "ROI Calculator",
    category: "product",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.SOLUTION,
    eventType: "solution",
    text: "Solution",
    category: "product",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.ROI.METHODOLOGY,
    eventType: "roi_methodology",
    text: "ROI Methodology",
    category: "product",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.FAQ,
    eventType: "faq",
    text: "FAQ",
    category: "product",
    showInHeader: false,
    showInMobile: true,
  },
  {
    href: RELATIVE_URLS.BLOG,
    eventType: "blog",
    text: "Blog",
    category: "product",
    showInHeader: true,
    showInMobile: true,
  },
  {
    href: RELATIVE_URLS.CONTACT,
    eventType: "contact",
    text: "Contact",
    category: "product",
    showInHeader: true,
    showInMobile: true,
  },

  // Dashboard
  {
    href: RELATIVE_URLS.DASHBOARD.COVERAGE_TRENDS,
    eventType: "coverage_trends",
    text: "Coverage Trends",
    category: "dashboard",
    showInHeader: true,
    showInMobile: true,
  },
  {
    href: RELATIVE_URLS.DASHBOARD.FILE_COVERAGE,
    eventType: "file_coverage",
    text: "File Coverage",
    category: "dashboard",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.DASHBOARD.CREDITS,
    eventType: "credits",
    text: "Credits",
    category: "dashboard",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.DASHBOARD.PRS,
    eventType: "prs",
    text: "Open PRs",
    category: "dashboard",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.DASHBOARD.USAGE,
    eventType: "usage",
    text: "Usage",
    category: "dashboard",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.DASHBOARD.TRIGGERS,
    eventType: "triggers",
    text: "Triggers",
    category: "dashboard",
    showInHeader: true,
    showInMobile: true,
  },
  {
    href: RELATIVE_URLS.DASHBOARD.ACTIONS,
    eventType: "actions",
    text: "Actions",
    category: "dashboard",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.DASHBOARD.REFERENCES,
    eventType: "references",
    text: "References",
    category: "dashboard",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.DASHBOARD.RULES,
    eventType: "rules",
    text: "Rules",
    category: "dashboard",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.DASHBOARD.INTEGRATIONS.CIRCLECI,
    eventType: "circleci_integration",
    text: "CircleCI Integration",
    category: "dashboard",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.DASHBOARD.INTEGRATIONS.NPM,
    eventType: "npm_integration",
    text: "npm Integration",
    category: "dashboard",
    showInHeader: false,
    showInMobile: false,
  },

  // Documentation
  {
    href: RELATIVE_URLS.DOCS.GETTING_STARTED.INSTALLATION,
    eventType: "docs_getting_started",
    text: "Getting Started",
    category: "docs",
    showInHeader: true,
    showInMobile: true,
  },
  {
    href: RELATIVE_URLS.DOCS.GETTING_STARTED.SETUP,
    eventType: "docs_setup",
    text: "Setup",
    category: "docs",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.DOCS.TRIGGERS.OVERVIEW,
    eventType: "docs_triggers",
    text: "Triggers",
    category: "docs",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.DOCS.COVERAGE.OVERVIEW,
    eventType: "docs_coverage",
    text: "Coverage Setup",
    category: "docs",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.DOCS.CUSTOMIZATION.REPOSITORY_RULES,
    eventType: "docs_customization",
    text: "Customization",
    category: "docs",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.DOCS.HOW_IT_WORKS.OVERVIEW,
    eventType: "docs_how_it_works",
    text: "How It Works",
    category: "docs",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.DOCS.ACTIONS.AUTO_MERGE,
    eventType: "docs_auto_merge",
    text: "Auto Merge",
    category: "docs",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.DOCS.INTEGRATIONS.CIRCLECI,
    eventType: "docs_circleci",
    text: "CircleCI",
    category: "docs",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.DOCS.INTEGRATIONS.NPM,
    eventType: "docs_npm",
    text: "npm",
    category: "docs",
    showInHeader: false,
    showInMobile: false,
  },

  // Legal
  {
    href: RELATIVE_URLS.PRIVACY_POLICY,
    eventType: "privacy_policy",
    text: "Privacy Policy",
    category: "legal",
    showInHeader: false,
    showInMobile: false,
  },
  {
    href: RELATIVE_URLS.TERMS_OF_SERVICE,
    eventType: "terms_of_service",
    text: "Terms of Service",
    category: "legal",
    showInHeader: false,
    showInMobile: false,
  },
] as const;

export type LinkCategory = "product" | "dashboard" | "docs" | "legal";
