export const KEYWORDS = [
  "AI",
  "artificial intelligence",
  "automated testing",
  "CI/CD",
  "code coverage",
  "code quality",
  "coding",
  "coding agent",
  "continuous integration",
  "developer tools",
  "git",
  "git auto",
  "git-auto",
  "gitauto",
  "github",
  "GitHub",
  "GitHub Actions",
  "pull requests",
  "QA Agent",
  "QA agent",
  "QA automation",
  "Quality Assurance",
  "Quality Assurance Agent",
  "software testing",
  "test automation",
  "test coverage",
  "test generation",
  "test-driven development",
  "testing tools",
  "TDD",
  "unit testing",
];
