import { DocsContact } from "@/app/components/docs/DocsContact";

export default function PrBodySummaryPage() {
  return (
    <>
      <h1 className="text-4xl font-bold mb-8">PR Body Summary</h1>

      <div className="space-y-12">
        <section>
          <p className="text-gray-600 mb-4">
            After GitAuto completes its work on a pull request, it generates a summary using Claude
            Sonnet 4.6 and appends it to the PR body. This gives reviewers immediate context about
            what was done, what bugs were found, and what needs their attention.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">Why This Exists</h2>
          <p className="text-gray-600 mb-4">
            When an AI agent creates or modifies a PR, the original body contains the issue
            description or schedule info but nothing about what actually happened during execution.
            Reviewers must piece together the story from the diff and comments. The PR body summary
            solves this by adding structured sections that explain the work at a glance.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">What Gets Generated</h2>
          <p className="text-gray-600 mb-4">
            The summary is generated by Claude using the full context of the agent&apos;s work: PR
            title, changed files with diffs, agent comments, and the agent&apos;s completion reason.
            The output includes these sections:
          </p>
          <ul className="list-disc pl-8 text-gray-600 space-y-2">
            <li>
              <strong>What I Tested</strong> - specific functions, behaviors, and edge cases covered
            </li>
            <li>
              <strong>Potential Bugs Found</strong> - edge cases, untested paths, or workarounds
              discovered during execution, and whether they were fixed or worked around
            </li>
            <li>
              <strong>Non-Code Tasks</strong> - tasks outside the code review such as env vars,
              migrations, or config changes
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">How It Works</h2>
          <p className="text-gray-600 mb-4">
            Each summary section is wrapped in HTML comment markers. If the agent runs again on the
            same PR, the section is replaced rather than duplicated. The original PR body is never
            modified - a horizontal rule separator is added before the first agent section.
          </p>
          <p className="text-gray-600 mb-4">
            The trigger type (dashboard, schedule, check suite, review comment) determines which
            marker and prompt are used, so different types of work produce appropriately structured
            summaries. Every generation call is recorded in our database for cost tracking.
          </p>
        </section>
      </div>

      <DocsContact />
    </>
  );
}
