name: E2E Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # https://docs.stripe.com/stripe-cli?install-method=apt#install
      - name: Install Stripe CLI
        run: |
          curl -s https://packages.stripe.dev/api/security/keypair/stripe-cli-gpg/public | gpg --dearmor | sudo tee /usr/share/keyrings/stripe.gpg
          echo "deb [signed-by=/usr/share/keyrings/stripe.gpg] https://packages.stripe.dev/stripe-cli-debian-local stable main" | sudo tee -a /etc/apt/sources.list.d/stripe.list
          sudo apt update
          sudo apt install stripe
          stripe --version

      # https://docs.stripe.com/stripe-cli?install-method=apt#login-account
      - name: Login to Stripe CLI
        run: stripe login --interactive --api-key ${{ secrets.STRIPE_SECRET_KEY }}

      - name: Run E2E tests
        run: npx playwright test
        env:
          NODE_ENV: test
          BASE_URL: http://localhost:4000

          # To ignore NextAuth warnings
          NEXTAUTH_URL: http://localhost:4000
          NEXTAUTH_SECRET: "dummy-secret-for-testing"

          # Stripe credentials for E2E tests
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}

          # Supabase credentials for E2E tests
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
