name: Generate OG Images

on:
  push:
    branches: [main]
    paths:
      - "app/**/page.tsx"
      - "app/components/**"
      - "styles/**"
  workflow_dispatch:

jobs:
  generate-og-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Build and start server
        run: |
          npm run build
          npm start &
          npx wait-on http://localhost:3000 --timeout 60000

      - name: Generate OG images for all pages
        run: node .github/scripts/generate-og-images.js

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/og/
          if ! git diff --staged --quiet; then
            git commit -m "chore: update OG images [skip ci]"
            git push
          fi
