name: Add Screenshot Comparison to PR

on:
  pull_request:

# Add these permissions at the top level
permissions:
  pull-requests: write
  contents: read

jobs:
  take-screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps chromium

      - name: Build project
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        run: npm run build

      # "&" starts the server in the background, don't wait for it to finish, and move on
      - name: Start local server
        run: npm run start &

      - name: Take screenshots (main)
        run: node scripts/take-screenshots.mjs main-screenshots/ https://gitauto.ai

      # This localhost:3000 is the local server we started earlier
      - name: Take screenshots (this branch)
        run: node scripts/take-screenshots.mjs branch-screenshots/ http://localhost:3000

      # https://github.com/actions/github-script
      - name: Post screenshot comparison
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // Get all comments for the pull request
            const comments = await github.rest.issues.listComments({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            // Delete previous comments created by this workflow
            for (const comment of comments.data) {
              console.log({ comment });
              if (comment.body.includes('Before (main) | After (this branch)')) {
                await github.rest.issues.deleteComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: comment.id
                });
              }
            }

            const mainDir = 'main-screenshots/';
            const branchDir = 'branch-screenshots/';

            const mainFiles = fs.readdirSync(mainDir).filter(file => file.endsWith('.png'));
            const branchFiles = fs.readdirSync(branchDir).filter(file => file.endsWith('.png'));

            for (let i = 0; i < mainFiles.length; i++) {
              const mainFile = mainFiles[i];
              const branchFile = branchFiles[i];
              const routePath = mainFile.replace('.png', '').replace(/_/g, '/');

              // Read and encode the images
              const mainImage = fs.readFileSync(path.join(mainDir, mainFile)).toString('base64');
              const branchImage = fs.readFileSync(path.join(branchDir, branchFile)).toString('base64');

              const body = `/${routePath}\n\n| Before (main) | After (this branch) |\n|--------------|---------------------|\n| <img src="data:image/png;base64,${mainImage}" width="400"/> | <img src="data:image/png;base64,${branchImage}" width="400"/> |`;

              github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              });
            }
