name: Slack PR Merge Notification

on:
  pull_request:
    types: [closed]

env:
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

jobs:
  notify-slack:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # https://github.com/gitautoai/website/settings/secrets/actions
      - name: Send Slack notification
        run: |
          jq -n \
            --arg title "${{ github.event.pull_request.title }}" \
            --arg url "${{ github.event.pull_request.html_url }}" \
            '{"channel": "C08PHH352S3", "text": "<!channel> Website PR Merged: <\($url)|\($title)>"}' | \
          curl -X POST -H "Authorization: Bearer $SLACK_BOT_TOKEN" -H 'Content-type: application/json' -d @- https://slack.com/api/chat.postMessage
